import type { Metadata } from "next";
import "./globals.css";
import FooterComponent from "@/components/Footer";
import NavMenuComponent from "@/components/nav-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#002626]">
        {/* Header component */}
        <NavMenuComponent />
        
        {/* Main content */}
        <main>{children}</main>

        {/* Footer component */}
        <FooterComponent />
      </body>
    </html>
  );
}
